id: PB77B4948
initial_creation_type: input
source_metadata:
  id: ''
  title: Akṣayamatinirdeśa
  language:
  - Tibetan
  - English
  - Sanskrit
  author: ''
created_at: '2022-01-13T12:13:25.209378'
last_modified_at: '2022-01-13T12:13:25.209386'
