id: PA9F39702
initial_creation_type: input
source_metadata:
  id: ''
  title: Akṣayamatinirdeśa
  language:
  - English
  - Tibetan
  - Sanskrit
  author: ''
created_at: '2022-01-10T11:50:51.441442'
last_modified_at: '2022-01-10T11:50:51.441449'
